apiVersion: apps/v1
kind: Deployment
metadata:
  name: arch-app
spec:
  selector:
    matchLabels:
      app: arch-app
  replicas: 4
  template:
    metadata:
      labels:
        app: arch-app
    spec:
      containers:
      - name: arch-app
        image: 000362764662.dkr.ecr.eu-north-1.amazonaws.com/arch-council/simple-svc:16
        ports:
        - containerPort: 8080
